vich_uploader:
    db_driver: orm

    mappings:
       dogs:
           uri_prefix: /images/dogs
           upload_destination: '%kernel.project_dir%/public/images/dogs'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
